apiRules:
- exclude:
    uidRegex: ^Tests
    type: Namespace
- exclude:
    uidRegex: .*Tests$
    type: Type
- exclude:
    uidRegex: .*Editor.*
    type: Type
- include:
    uidRegex: ^Barista
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace