name: Build and Deploy Documentation

on:
  push:
    branches: [ master, main ]  
    paths:
      - 'Documentation/**'      
      - 'Assets/**/*.cs'        
  workflow_dispatch:            

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Setup DocFX
        run: dotnet tool update -g docfx

      - name: Build Documentation
        run: |
          cp README.md Documentation/index.md
          docfx Documentation/docfx.json

      - name: Create .nojekyll
        run: touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          clean: true