name: Build and Deploy Documentation
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  # Сборка документации
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install DocFX
        run: choco install -y docfx

      - name: Use README.md as index.md
        run: copy README.md Documentation\index.md
        shell: cmd

      - name: Build
        run: docfx Documentation/docfx.json

      - name: Create .nojekyll file
        run: type nul > _site/.nojekyll
        shell: cmd
        
      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: _site

  # Деплой документации в ветку gh-pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: _site
          path: _site

      # Создаем .nojekyll снова после загрузки артефакта
      - name: Create .nojekyll file
        run: touch _site/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site